### PR TITLE
v1

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
- Introduces `Sandbox` concept
- Deprecates `.defer()`
- Simplified logic
- Replaces `.onError` with `catch`
- Introduces `.measure()` and `.mutate()` aliases for `.read()` and `.write()`

**Comment by wilsonpage** [comment]
+@adaroseedwards

**Comment by wilsonpage** [comment]
+@pornel to review. Any 'jank' related stuff can be layered on top of this.

**Comment by wilsonpage** [comment]
PS. need to squash this shit.

**Comment by orangemug** [comment]
@wilsonpage why the 2 files (they look very similar)

    ./lib/fastdom.js
    ./fastdom.js

**Comment by wilsonpage** [comment]
@orangemug one is src and the other is dist. Although if you're running in CommonJS env you can just use src.

**Comment by orangemug** [comment]
Ah it's generated https://github.com/wilsonpage/fastdom/blob/v1-beta/package.json#L8, that was confusing. Maybe it should be in a `./dist` directory?

Alternatively just remove it entirely and provide a link to https://wzrd.in/standalone/fastdom@latest

**Comment by wilsonpage** [comment]
Wow that's really cool! I wanted the dist to be in the root directory to make it super clear to users which file they should be using.

**Comment by orangemug** [comment]
The downside is that it's not clear which files people should make pull requests against though. You could add a small header as a polite note to the compiled version.
 
    cat polite_note.txt lib/fastdom.js | ./node_modules/.bin/browserify - > fastdom.js

Where `polite_note.txt` is

    /**
     * I am a compiled file, please don't me!
     */ 

Although you probably wouldn't want `polite_note.txt` in the base dir :)...

**Comment by wilsonpage** [comment]
Yeah I agree. It's a bit of a toss-up I guess. We could just compress the `/fastdom.js` dist so that it's obvious it's a built file? And remove the `fastdom.min.js`

**Comment by orangemug** [comment]
I assume people still like the un-minified version of files for dev? (not sure though). Really all I care about is knowing for sure which file is the one to edit for a PR.

**Comment by wilsonpage** [comment]
I think this is ready to land. Any objections?

**Comment by pornel** [comment]
LGTM :)

**Pull request merged**
